package com.example.ui.editor

object Locales {
    private val translations = mapOf(
        "en" to mapOf(
            "properties" to "PROPERTIES",
            "basic" to "Basic Properties",
            "name" to "Name",
            "parent" to "Parent",
            "visible" to "Visible",
            "background_color" to "Background Color",
            "background_transparency" to "Background Transparency",
            "border_size_pixel" to "Border Size Pixel",
            "text_settings" to "Text Settings",
            "text" to "Text",
            "text_color" to "Text Color",
            "text_size" to "Text Size",
            "text_transparency" to "Text Transparency",
            "text_wrapped" to "Text Wrapped",
            "text_scaled" to "Text Scaled",
            "font" to "Font",
            "size" to "Size",
            "position" to "Position",
            "rotation" to "Rotation",
            "corner_radius" to "Corner Radius",
            "image_settings" to "Image Settings",
            "image" to "Image ID",
            "image_transparency" to "Image Transparency",
            "scale_type" to "Scale Type",
            "export_luau" to "Export Roblox Luau Script",
            "copy_clipboard" to "Copy to Clipboard",
            "share" to "Share",
            "close" to "Close",
            "adv_gradient_title" to "Advanced Gradient Stop Editor",
            "gradient_preview" to "Gradient Preview",
            "gradient_track" to "Gradient Stops Track",
            "click_to_add" to "Click track to add • Drag nodes",
            "stop_color_settings" to "Stop Color Settings",
            "stop_position" to "Stop Position",
            "visual_color_mixer" to "Visual Color Mixer",
            "hue" to "Hue",
            "saturation" to "Saturation",
            "brightness" to "Brightness",
            "hex" to "HEX",
            "save_close" to "Save & Close",
            "cancel" to "Cancel",
            "delete_stop" to "Delete Stop",
            "export" to "Export",
            "undo" to "Undo",
            "redo" to "Redo",
            "add_child" to "Add Child",
            "delete" to "Delete",
            "preview" to "Preview",
            "edit_script" to "Edit Script",
            "save_code" to "Save Code",
            "active" to "Active",
            "z_index" to "ZIndex",
            "layout_order" to "LayoutOrder",
            "clips_descendants" to "ClipsDescendants",
            "anchor_point" to "AnchorPoint",
            "scrolling_direction" to "ScrollingDirection",
            "canvas_size" to "CanvasSize",
            "scrollbar_thickness" to "ScrollBarThickness",
            "fill_direction" to "FillDirection",
            "horizontal_alignment" to "HorizontalAlignment",
            "vertical_alignment" to "VerticalAlignment",
            "padding" to "Padding",
            "sort_order" to "SortOrder",
            "cell_padding" to "CellPadding",
            "cell_size" to "CellSize",
            "corner_radius_val" to "CornerRadius",
            "stroke_color" to "Stroke Color",
            "thickness" to "Thickness",
            "apply_stroke_mode" to "ApplyStrokeMode",
            "rotation_val" to "Rotation",
            "transparency" to "Transparency",
            "scale" to "Scale",
            "aspect_ratio" to "AspectRatio",
            "aspect_type" to "AspectType",
            "dominant_axis" to "DominantAxis",
            "shadow_color" to "Shadow Color",
            "shadow_blur" to "Shadow Blur",
            "shadow_spread" to "Shadow Spread",
            "shadow_offset" to "Shadow Offset",
            "shadow_enabled" to "Shadow Enabled",
            "point" to "Point"
        ),
        "vi" to mapOf(
            "properties" to "THUỘC TÍNH",
            "basic" to "Thuộc tính cơ bản",
            "name" to "Tên đối tượng",
            "parent" to "Đối tượng cha",
            "visible" to "Hiển thị",
            "background_color" to "Màu nền",
            "background_transparency" to "Độ trong suốt nền",
            "border_size_pixel" to "Độ rộng viền (Px)",
            "text_settings" to "Cài đặt văn bản",
            "text" to "Nội dung chữ",
            "text_color" to "Màu chữ",
            "text_size" to "Cỡ chữ",
            "text_transparency" to "Độ trong suốt chữ",
            "text_wrapped" to "Tự động xuống dòng",
            "text_scaled" to "Tự động co giãn",
            "font" to "Phông chữ",
            "size" to "Kích thước (Size)",
            "position" to "Vị trí (Position)",
            "rotation" to "Góc xoay",
            "corner_radius" to "Bo góc (Corner)",
            "image_settings" to "Cài đặt hình ảnh",
            "image" to "Mã ảnh (Image ID)",
            "image_transparency" to "Độ trong suốt ảnh",
            "scale_type" to "Kiểu co giãn ảnh",
            "export_luau" to "Xuất mã Roblox Luau",
            "copy_clipboard" to "Sao chép bộ nhớ",
            "share" to "Chia sẻ",
            "close" to "Đóng",
            "adv_gradient_title" to "Trình Chỉnh Sửa Gradient Nâng Cao",
            "gradient_preview" to "Xem trước Gradient",
            "gradient_track" to "Thanh điểm màu Gradient",
            "click_to_add" to "Nhấn thanh để thêm • Kéo điểm để di chuyển",
            "stop_color_settings" to "Cài đặt điểm màu",
            "stop_position" to "Vị trí điểm màu",
            "visual_color_mixer" to "Phối màu trực quan",
            "hue" to "Tông màu (Hue)",
            "saturation" to "Độ bão hòa (Saturation)",
            "brightness" to "Độ sáng (Brightness)",
            "hex" to "Mã HEX",
            "save_close" to "Lưu & Đóng",
            "cancel" to "Hủy bỏ",
            "delete_stop" to "Xóa điểm màu",
            "export" to "Xuất mã",
            "undo" to "Hoàn tác",
            "redo" to "Làm lại",
            "add_child" to "Thêm đối tượng con",
            "delete" to "Xóa đối tượng",
            "preview" to "Xem trước",
            "edit_script" to "Sửa mã Script",
            "save_code" to "Lưu mã nguồn",
            "active" to "Kích hoạt",
            "z_index" to "Thứ tự hiển thị (ZIndex)",
            "layout_order" to "Thứ tự sắp xếp",
            "clips_descendants" to "Cắt nội dung tràn",
            "anchor_point" to "Tâm neo (AnchorPoint)",
            "scrolling_direction" to "Hướng cuộn trang",
            "canvas_size" to "Kích thước cuộn",
            "scrollbar_thickness" to "Độ dày thanh cuộn",
            "fill_direction" to "Hướng sắp xếp",
            "horizontal_alignment" to "Sắp xếp hàng ngang",
            "vertical_alignment" to "Sắp xếp hàng dọc",
            "padding" to "Khoảng đệm (Padding)",
            "sort_order" to "Quy tắc sắp xếp",
            "cell_padding" to "Khoảng cách ô",
            "cell_size" to "Kích thước ô",
            "corner_radius_val" to "Bán kính bo góc",
            "stroke_color" to "Màu nét vẽ",
            "thickness" to "Độ dày nét",
            "apply_stroke_mode" to "Chế độ nét vẽ",
            "rotation_val" to "Góc xoay",
            "transparency" to "Độ trong suốt",
            "scale" to "Tỉ lệ co giãn",
            "aspect_ratio" to "Tỉ lệ khung hình",
            "aspect_type" to "Loại khung hình",
            "dominant_axis" to "Trục ưu tiên",
            "shadow_color" to "Màu bóng đổ",
            "shadow_blur" to "Độ mờ bóng đổ",
            "shadow_spread" to "Độ lan bóng đổ",
            "shadow_offset" to "Khoảng lệch bóng",
            "shadow_enabled" to "Bật bóng đổ",
            "point" to "Điểm"
        )
    )

    fun translate(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
